UPDATE public.areas
SET map = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="-0.5 -0.5 870 900" xml:space="preserve">
<style type="text/css">
	.st0{fill:#BABABA;}
	.st1{fill:#DCEBFA;}
	.st2{fill:#9B9B9B;}
	.st3{fill:#E2E2E2;}
	.st4{fill:#FFFFFF; pointer-events: none;}
	.st5{font-family:''Helvetica'';}
	.st6{font-size:20px;}
	.st7{font-size:25px;}
	.st8{opacity:0;}
</style>

<rect x="0" y="-0.5" width="880" class="st0" height="902.5" fill="#b3b3b3" stroke="#b3b3b3" pointer-events="all"/>
<rect x="40" y="32" width="180" class="st2" height="180" rx="27" ry="27" fill="#c9c9c9" stroke="#c9c9c9" pointer-events="all"/>

<rect x="450" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-59"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 451px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">59</div></div></div></foreignObject><text class="noClick" x="470" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">59</text></switch></g>

<rect x="610" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-54"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 611px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">54</div></div></div></foreignObject><text class="noClick" x="630" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">54</text></switch></g>

<rect x="660" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all"  id="seat-51"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 661px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">51</div></div></div></foreignObject><text class="noClick" x="680" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">51</text></switch></g>

<rect x="610" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all"  id="seat-53"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 611px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">53</div></div></div></foreignObject><text class="noClick" x="630" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">53</text></switch></g>

<rect x="660" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all"  id="seat-50"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 661px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">50</div></div></div></foreignObject><text class="noClick" x="680" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">50</text></switch></g>

<rect x="610" y="172" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all"  id="seat-52"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 192px; margin-left: 611px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">52</div></div></div></foreignObject><text class="noClick" x="630" y="200" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">52</text></switch></g>

<rect x="660" y="172" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all"  id="seat-49"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 192px; margin-left: 661px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">49</div></div></div></foreignObject><text class="noClick" x="680" y="200" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">49</text></switch></g>

<rect x="750" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all"  id="seat-48"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">48</div></div></div></foreignObject><text class="noClick" x="770" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">48</text></switch></g>

<rect x="800" y="122" class="seat st8"  width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-45"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">45</div></div></div></foreignObject><text class="noClick" x="820" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">45</text></switch></g>

<rect x="750" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-47"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">47</div></div></div></foreignObject><text class="noClick" x="770" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">47</text></switch></g>

<rect x="800" y="232" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-44"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 252px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">44</div></div></div></foreignObject><text class="noClick" x="820" y="260" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">44</text></switch></g>

<rect x="800" y="282" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-43"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 302px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">43</div></div></div></foreignObject><text class="noClick" x="820" y="310" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">43</text></switch></g>

<rect x="800" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" pointer-events="all" id="seat-46"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">46</div></div></div></foreignObject><text class="noClick" x="820" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">46</text></switch></g>

<rect x="750" y="232" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-42"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 252px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">42</div></div></div></foreignObject><text class="noClick" x="770" y="260" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">42</text></switch></g>

<rect x="800" y="412" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-39"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 432px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">39</div></div></div></foreignObject><text class="noClick" x="820" y="440" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">39</text></switch></g>

<rect x="750" y="362" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-38"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 382px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">38</div></div></div></foreignObject><text class="noClick" x="770" y="390" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">38</text></switch></g>

<rect x="750" y="282" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-41"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 302px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">41</div></div></div></foreignObject><text class="noClick" x="770" y="310" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">41</text></switch></g>

<rect x="750" y="412" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-37"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 432px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">37</div></div></div></foreignObject><text class="noClick" x="770" y="440" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">37</text></switch></g>

<rect x="800" y="362" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-40"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 382px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">40</div></div></div></foreignObject><text class="noClick" x="820" y="390" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">40</text></switch></g>

<rect x="800" y="492" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-36"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 512px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">36</div></div></div></foreignObject><text class="noClick" x="820" y="520" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">36</text></switch></g>

<rect x="40" y="232" class="st2" width="160" height="80" rx="12" ry="12" stroke="#9e9e9e" pointer-events="all"/>
<rect x="40" y="322" class="st2" width="270" height="240" rx="36" ry="36" stroke="#9e9e9e" pointer-events="all"/>
<rect x="40" y="572" class="st1" width="160" height="80" rx="12" ry="12" stroke="#d9d9d9" pointer-events="all"/>
<rect x="40" y="372" class="st1" width="110" height="140" rx="16.5" ry="16.5" stroke="#d9d9d9d9" pointer-events="all"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 108px; height: 1px; padding-top: 442px; margin-left: 41px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: #000000; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; "><font style="font-size: 26px" face="Verdana" color="#454545">WC</font></div></div></div></foreignObject><text class="noClick" x="95" y="446" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle">WC</text></switch></g>

<rect x="220" y="342" class="st1" width="60" height="20" rx="3" ry="3" fill="#b3b3b3" stroke="#b3b3b3" pointer-events="all"/>
<path d="M 245 342 L 255 352 L 245 362 Z" class="st2" stroke="#e6e6e6" stroke-miterlimit="10" transform="rotate(-90,250,352)" pointer-events="all"/>
<rect x="220" y="522" class="st1" width="60" height="20" rx="3" ry="3" fill="#b3b3b3" stroke="#b3b3b3" pointer-events="all"/>
<path d="M 245 522 L 255 532 L 245 542 Z" class="st2" stroke="#e6e6e6" stroke-miterlimit="10" transform="rotate(90,250,532)" pointer-events="all"/>

<rect x="320" y="322" class="st0" width="280" height="240" rx="36" ry="36" stroke="#d9d9d9d9" pointer-events="all"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 278px; height: 1px; padding-top: 442px; margin-left: 321px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: #000000; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; "><font><font color="#454545"><font face="Verdana"><font style="font-size: 45px">Tower</font><br/>
</font></font><font face="Verdana"><span style="font-size: 45px">12</span></font><br />
</font></div></div></div></foreignObject><text class="noClick" x="460" y="446" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle" class="st4 st5 st7">Tower...</text></switch></g>

<rect x="800" y="622" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-32"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 642px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">32</div></div></div></foreignObject><text class="noClick" x="820" y="650" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">32</text></switch></g>

<rect x="750" y="492" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-34"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 512px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">34</div></div></div></foreignObject><text class="noClick" x="770" y="520" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">34</text></switch></g>

<rect x="800" y="672" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-31"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 692px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">31</div></div></div></foreignObject><text class="noClick" x="820" y="700" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">31</text></switch></g>

<rect x="750" y="542" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-33"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 562px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">33</div></div></div></foreignObject><text class="noClick" x="770" y="570" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">33</text></switch></g>

<rect x="800" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-28"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">28</div></div></div></foreignObject><text class="noClick" x="820" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">28</text></switch></g>

<rect x="750" y="622" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-30"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 642px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">30</div></div></div></foreignObject><text class="noClick" x="770" y="650" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">30</text></switch></g>

<rect x="750" y="672" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-29"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 692px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">29</div></div></div></foreignObject><text class="noClick" x="770" y="700" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">29</text></switch></g>

<rect x="800" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-27"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">27</div></div></div></foreignObject><text class="noClick" x="820" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">27</text></switch></g>

<rect x="750" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-26"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">26</div></div></div></foreignObject><text class="noClick" x="770" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">26</text></switch></g>

<rect x="620" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-23"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 621px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">23</div></div></div></foreignObject><text class="noClick" x="640" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">23</text></switch></g>

<rect x="140" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-4"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 141px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 12px; font-family: Helvetica; color: #000000; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; "><font style="font-size: 25px" color="#ffffff">4</font></div></div></div></foreignObject><text class="noClick" x="160" y="786" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle">4</text></switch></g>

<rect x="190" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-6"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 191px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 12px; font-family: Helvetica; color: #000000; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; "><font style="font-size: 25px" color="#ffffff">6</font></div></div></div></foreignObject><text class="noClick" x="210" y="786" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle">6</text></switch></g>

<rect x="190" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-5"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 191px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 12px; font-family: Helvetica; color: #000000; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; "><font style="font-size: 25px" color="#ffffff">5</font></div></div></div></foreignObject><text class="noClick" x="210" y="736" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle">5</text></switch></g>

<rect x="310" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-7"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 311px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 12px; font-family: Helvetica; color: #000000; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; "><font style="font-size: 25px" color="#ffffff">7</font></div></div></div></foreignObject><text class="noClick" x="330" y="736" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle">7</text></switch></g>

<rect x="310" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-8"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 311px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">8</div></div></div></foreignObject><text class="noClick" x="330" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">8</text></switch></g>

<rect x="360" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-10"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 361px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">10</div></div></div></foreignObject><text class="noClick" x="380" y="740" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">10</text></switch></g>

<rect x="310" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-9"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 311px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">9</div></div></div></foreignObject><text class="noClick" x="330" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">9</text></switch></g>

<rect x="360" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-11"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 361px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">11</div></div></div></foreignObject><text class="noClick" x="380" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">11</text></switch></g>

<rect x="570" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-21"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 571px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">21</div></div></div></foreignObject><text class="noClick" x="590" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">21</text></switch></g>

<rect x="620" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-24"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 621px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">24</div></div></div></foreignObject><text class="noClick" x="640" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">24</text></switch></g>

<rect x="490" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-18"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 491px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">18</div></div></div></foreignObject><text class="noClick" x="510" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">18</text></switch></g>

<rect x="570" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-19"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 571px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">19</div></div></div></foreignObject><text class="noClick" x="590" y="740" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">19</text></switch></g>

<rect x="570" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-20"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 571px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">20</div></div></div></foreignObject><text class="noClick" x="590" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">20</text></switch></g>

<rect x="360" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-12"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 361px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">12</div></div></div></foreignObject><text class="noClick" x="380" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">12</text></switch></g>

<rect x="440" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-14"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 441px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">14</div></div></div></foreignObject><text class="noClick" x="460" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">14</text></switch></g>

<rect x="440" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-15"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 441px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">15</div></div></div></foreignObject><text class="noClick" x="460" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">15</text></switch></g>

<rect x="490" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-16"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 491px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">16</div></div></div></foreignObject><text class="noClick" x="510" y="740" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">16</text></switch></g>

<rect x="440" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-13"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 441px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">13</div></div></div></foreignObject><text class="noClick" x="460" y="740" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">13</text></switch></g>

<image x="79.5" y="571.5" width="70" height="70" xlink:href="https://cdn2.iconfinder.com/data/icons/barista/256/barista-icons_americano-128.png" preserveAspectRatio="none"/>

<rect x="530" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-56"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 531px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">56</div></div></div></foreignObject><text class="noClick" x="550" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">56</text></switch></g>

<rect x="450" y="172" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-58"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 192px; margin-left: 451px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">58</div></div></div></foreignObject><text class="noClick" x="470" y="200" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">58</text></switch></g>

<rect x="530" y="172" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-55"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 192px; margin-left: 531px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">55</div></div></div></foreignObject><text class="noClick" x="550" y="200" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">55</text></switch></g>

<rect x="60" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-1"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 61px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">1</div></div></div></foreignObject><text class="noClick" x="80" y="740" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">1</text></switch></g>

<rect x="800" y="542" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-35"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 562px; margin-left: 801px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">35</div></div></div></foreignObject><text class="noClick" x="820" y="570" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">35</text></switch></g>

<rect x="490" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-17"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 491px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">17</div></div></div></foreignObject><text class="noClick" x="510" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">17</text></switch></g>

<rect x="620" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-22"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 621px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">22</div></div></div></foreignObject><text class="noClick" x="640" y="740" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">22</text></switch></g>

<rect x="750" y="812" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-25"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 832px; margin-left: 751px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">25</div></div></div></foreignObject><text class="noClick" x="770" y="840" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">25</text></switch></g>

<rect x="60" y="762" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-2"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 782px; margin-left: 61px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">2</div></div></div></foreignObject><text class="noClick" x="80" y="790" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">2</text></switch></g>

<rect x="140" y="712" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-3"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 732px; margin-left: 141px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">3</div></div></div></foreignObject><text class="noClick" x="160" y="740" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">3</text></switch></g>

<rect x="530" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-57"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 531px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">57</div></div></div></foreignObject><text class="noClick" x="550" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">57</text></switch></g>

<rect x="450" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-60"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 451px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">60</div></div></div></foreignObject><text class="noClick" x="470" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">60</text></switch></g>

<rect x="400" y="172" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-61"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 192px; margin-left: 401px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">61</div></div></div></foreignObject><text class="noClick" x="420" y="200" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">61</text></switch></g>

<rect x="400" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-62"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 401px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">62</div></div></div></foreignObject><text class="noClick" x="420" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">62</text></switch></g>

<rect x="400" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-63"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 401px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">63</div></div></div></foreignObject><text class="noClick" x="420" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">63</text></switch></g>

<rect x="320" y="172" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-64"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 192px; margin-left: 321px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">64</div></div></div></foreignObject><text class="noClick" x="340" y="200" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">64</text></switch></g>

<rect x="320" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-65"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 321px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">65</div></div></div></foreignObject><text class="noClick" x="340" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">65</text></switch></g>

<rect x="320" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-66"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 321px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">66</div></div></div></foreignObject><text class="noClick" x="340" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">66</text></switch></g>

<rect x="270" y="72" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-68"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 92px; margin-left: 271px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">68</div></div></div></foreignObject><text class="noClick" x="290" y="100" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">68</text></switch></g>

<rect x="270" y="122" class="seat st8" width="40" height="40" rx="6" ry="6" stroke="#e6e6e6" pointer-events="all" id="seat-67"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 142px; margin-left: 271px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">67</div></div></div></foreignObject><text class="noClick" x="290" y="150" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">67</text></switch></g>

<rect x="110" y="102" class="seat st8" width="40" height="40" rx="6" ry="6" id="seat-69"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 122px; margin-left: 111px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div class="st4 st5 st6" style="display: inline-block; font-size: 25px; font-family: Helvetica; color: #FFFFFF; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; ">69</div></div></div></foreignObject><text class="noClick" x="130" y="130" fill="#FFFFFF" font-family="Helvetica" font-size="25px" text-anchor="middle">69</text></switch></g>

<rect x="170" y="794" class="st2" width="210" height="5" rx="0.75" ry="0.75" stroke="#9e9e9e" transform="rotate(-90,275,796.5)" pointer-events="all"/>

<rect x="405" y="872" width="110" height="30" fill="#b3b3b3" stroke="#b3b3b3" pointer-events="all"/>
<g transform="translate(-0.5 -0.5)"><switch><foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 108px; height: 1px; padding-top: 887px; margin-left: 406px;"><div style="box-sizing: border-box; font-size: 0; text-align: center; "><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: #000000; line-height: 1.2; pointer-events: all; white-space: normal; word-wrap: normal; "><font style="font-size: 18px">Rotherstraße</font></div></div></div></foreignObject><text class="noClick" x="460" y="891" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle">Rotherstraße</text></switch></g>

</svg>'
WHERE "floorId" in (10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25)
  AND "code" = 'GH';

